title: Raleigh
google_api_key:  AIzaSyCg4JXD_1a4_Ywz-xUkRI5-5EyB9oeGBeA 

email: discover.of.wf@gmail.com
url: rnsda.github.io
#description:None
# User setting
owner: Raleigh North SDA
facebook_username: 
twitter_username:
github_username:
church: 257 Friendship Chapel, Wake Forest, NC
location: 3808 Rogers Rd WAKE FOREST NC 27587
mail: '3650 Rogers Road # 336 Wake Forest NC 27587'
address:
  - line: "3650 Rogers Road # 336 Wake Forest NC 27587"
  # Feel free to add more lines here 
telephone:
copyright:

# API settings

# Build settings
markdown: kramdown
