title:Raleigh
email:discover.of.wf@gmail.com
url:brh.github.io/rnsdabuilding
description:None
# User setting
owner: Raleigh North SDA
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:AIzaSyBvo7wXrqOvgcUDg8kC0a_CuVcp65mp8eI

# Build settings
markdown: kramdown
