title: Raleigh
google_api_key: AIzaSyBvo7wXrqOvgcUDg8kC0a_CuVcp65mp8eI
email: discover.of.wf@gmail.com
url:brh.github.io/rnsdabuilding
description:None
# User setting
owner: Raleigh North SDA
email:
facebook_username:
twitter_username:
github_username:
address:
  - line: 5505 Six Forks Rd, Raleigh, NC 27614
  # Feel free to add more lines here 
telephone:
copyright:

# API settings

# Build settings
markdown: kramdown
